# Generated by Selenium IDE
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from NewsTailorDjangoApplication.tests.selenium.aut_acceptance_tests.test_sign_in import sign_in
from NewsTailorDjangoApplication.tests.selenium.aut_acceptance_tests.test_signup import sign_up


class TestGenerate:
    def setup_method(self):
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--remote-debugging-port=9222")

        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_generate(self):
        sign_up(self)
        sign_in(self)
        config_form_input = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".configuration-form-input:nth-child(3)"))
        )
        config_form_input.click()

        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(3)")
        dropdown.find_element(By.XPATH, "//option[. = 'Sources']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".source-selection").click()
        self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(2)").click()
        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(2)")
        dropdown.find_element(By.XPATH, "//option[. = 'Last 3 days']").click()
