version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  newstailor_fe:
    image: newstailor_fe:latest
    container_name: newstailor_fe
    ports:
      - "5173:5173" 

  newstailor_be:
    image: newstailor_be:latest
    container_name: newstailor_be
    ports:
      - "5273:5273" 


volumes:
  postgres_data:
