app = 'newstailorbe-prod'
primary_region = 'mad'
console_command = '/code/manage.py shell'

[requires]
python_version = "3.10"

[build]

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
  PORT = '8000'
  AUTO_DESTROY = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
