# fly.toml app configuration file generated for newstailorbe on 2024-12-04T19:18:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'newstailorbe'
primary_region = 'mad'
console_command = '/code/manage.py shell'

[requires]
python_version = "3.10"

[build]

[deploy]
release_command = "python manage.py migrate --noinput"
[env]
  AUTO_DESTROY = "false"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
