# Generated by Django 4.2.16 on 2024-11-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewsTailorDjangoApplication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wpm",
            field=models.IntegerField(default=238),
        ),
    ]
