# Generated by Django 4.2.16 on 2024-11-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "NewsTailorDjangoApplication",
            "0002_remove_newspaper_newsarticle_newsarticle_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="generated_using",
        ),
    ]
