# Generated by Django 4.2.16 on 2024-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewsTailorDjangoApplication", "0003_remove_newspaper_generated_using"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
