# Generated by Django 4.2.16 on 2024-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewsTailorDjangoApplication", "0004_alter_newspaper_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="is_currently_reading",
            field=models.BooleanField(default=False),
        ),
    ]
