# Generated by Django 4.2.16 on 2024-11-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NewsTailorDjangoApplication", "0002_user_wpm"),
        ("NewsTailorDjangoApplication", "0005_newspaper_is_currently_reading"),
    ]

    operations = []
