# Generated by Django 4.2.16 on 2024-11-17 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0006_merge_20241115_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Configuration_Source',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
