# Generated by Django 4.2.16 on 2024-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0006_merge_20241115_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
