# Generated by Django 4.2.16 on 2024-11-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0007_configuration_sources_delete_configuration_source_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuration',
            table='configuration',
        ),
    ]
