# Generated by Django 4.2.16 on 2024-11-17 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0008_alter_configuration_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='configuration_category',
            old_name='configuration_id',
            new_name='configuration',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='user_configuration',
            field=models.ForeignKey(db_column='user_configuration', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
