# Generated by Django 4.2.16 on 2024-11-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NewsTailorDjangoApplication", "0007_newspaper_is_saved"),
        (
            "NewsTailorDjangoApplication",
            "0009_rename_category_id_configuration_category_category_and_more",
        ),
    ]

    operations = []
