# Generated by Django 4.2.16 on 2024-12-01 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0010_merge_20241119_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration_User_Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField()),
                ('user_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuration_newspaper',
            },
        ),
    ]
