# Generated by Django 4.2.16 on 2024-12-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0011_configuration_user_newspaper'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuration_user_newspaper',
            table='configuration_user_newspaper',
        ),
    ]
