# Generated by Django 4.2.16 on 2024-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsTailorDjangoApplication', '0013_configuration_user_newspaper_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_user_newspaper',
            name='margin_size',
            field=models.IntegerField(default=16),
        ),
    ]
