# Generated by Django 4.2.16 on 2025-01-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "NewsTailorDjangoApplication",
            "0014_configuration_user_newspaper_margin_size",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wpm",
            field=models.IntegerField(default=250),
        ),
    ]
