app = 'newstailorreactapplication-prod'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 6173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
