# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class Test005signup:
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_005signup(self):
    # Test name: 005_sign_up
    # Step # | name | target | value
    # 1 | open | http://localhost:5173/ | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1920x804 | 
    self.driver.set_window_size(1920, 804)
    # 3 | click | css=.auth-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
    # 4 | click | css=.auth-panel-left .auth-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-panel-left .auth-btn").click()
    # 5 | click | css=.sign-up-form > .signin-signup-input-field:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-up-form > .signin-signup-input-field:nth-child(2)").click()
    # 6 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 7 | type | name=username | username
    self.driver.find_element(By.NAME, "username").send_keys("username")
    # 8 | type | name=password1 | User00$$$$$
    self.driver.find_element(By.NAME, "password1").send_keys("User00$$$$$")
    # 9 | type | name=email | username@gmail.com
    self.driver.find_element(By.NAME, "email").send_keys("username@gmail.com")
    # 10 | click | name=password1 | 
    self.driver.find_element(By.NAME, "password1").click()
    # 11 | click | name=password2 | 
    self.driver.find_element(By.NAME, "password2").click()
    # 12 | type | name=password2 | User00$$$$$
    self.driver.find_element(By.NAME, "password2").send_keys("User00$$$$$")
    # 13 | click | css=.auth-btn:nth-child(6) | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-btn:nth-child(6)").click()
    # 14 | click | css=.sign-in-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form").click()
  
