# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class Test009ViewProfile:
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_009_view_profile(self):
    # Test name: 009_view_profile
    # Step # | name | target | value
    # 1 | open | http://localhost:5173/ | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1512x945 | 
    self.driver.set_window_size(1512, 945)
    # 3 | click | css=.auth-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
    # 4 | mouseOver | css=.auth-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".auth-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2)").click()
    # 6 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").click()
    # 7 | type | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | username@gmail.com
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").send_keys("username@gmail.com")
    # 8 | type | name=password | User00$$$$$
    self.driver.find_element(By.NAME, "password").send_keys("User00$$$$$")
    # 9 | click | css=.solid | 
    self.driver.find_element(By.CSS_SELECTOR, ".solid").click()
    # 10 | click | linkText=Profile | 
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
  
