# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By

class Test006signin:
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_006signin(self):
    # Test name: 006_sign_in
    # Step # | name | target | value
    # 1 | open | http://localhost:5173/ | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1512x945 | 
    self.driver.set_window_size(1512, 945)
    # 3 | click | css=.auth-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
    # 4 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").click()
    # 5 | type | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | username@gmail.com
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").send_keys("username@gmail.com")
    # 6 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 7 | type | name=password | User00$$$$$
    self.driver.find_element(By.NAME, "password").send_keys("User00$$$$$")
    # 8 | click | css=.solid | 
    self.driver.find_element(By.CSS_SELECTOR, ".solid").click()
    # 9 | click | css=.content-table | 
    self.driver.find_element(By.CSS_SELECTOR, ".content-table").click()
  
