# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

class Test010EditProfile:
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_010_edit_profile(self):
    # Test name: 010_edit_profile
    # Step # | name | target | value
    # 1 | open | http://localhost:5173/ | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1512x945 | 
    self.driver.set_window_size(1512, 945)
    # 3 | click | css=.auth-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
    # 4 | mouseOver | css=.auth-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".auth-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").click()
    # 6 | type | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | username@gmail.com
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").send_keys("username@gmail.com")
    # 7 | type | name=password | User00$$$$$
    self.driver.find_element(By.NAME, "password").send_keys("User00$$$$$")
    # 8 | sendKeys | name=password | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    # 9 | click | linkText=Profile | 
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    # 10 | click | css=button > .icon | 
    self.driver.find_element(By.CSS_SELECTOR, "button > .icon").click()
    # 11 | mouseDownAt | id=email | -29,27.5
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 12 | mouseMoveAt | id=email | -29,27.5
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | mouseUpAt | id=email | -29,27.5
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 14 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 15 | type | id=email | user@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("user@gmail.com")
    # 16 | click | css=.blue-circle-button-submit | 
    self.driver.find_element(By.CSS_SELECTOR, ".blue-circle-button-submit").click()
  
