# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from NewsTailorDjangoApplication.tests.automated_tests.test_main_page_buttons import sign_in


class TestConfiguration:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_configuration(self):
        sign_in(self)
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "templateLink"))
        ).click()
        self.driver.find_element(By.ID, "template-name").click()
        self.driver.find_element(By.ID, "template-name").send_keys("name")
        self.driver.find_element(By.CSS_SELECTOR, ".timeline-selection > .configuration-form-input").click()
        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".timeline-selection > .configuration-form-input")
        dropdown.find_element(By.XPATH, "//option[. = 'Last Day']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(3)").click()
        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(3)")
        dropdown.find_element(By.XPATH, "//option[. = 'Sources']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".source-select").click()
        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".source-select")
        dropdown.find_element(By.XPATH, "//option[. = 'Category']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-button").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
