# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestSignin:
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_signin(self):
    # Test name: sign_in
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1472x911 | 
    self.driver.set_window_size(1472, 911)
    # 3 | click | css=.auth-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
    # 4 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2)").click()
    # 5 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2)").click()
    # 6 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").click()
    # 7 | type | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | user@gmail.com
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").send_keys("user@gmail.com")
    # 8 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(3)").click()
    # 9 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 10 | type | name=password | 12345Aa!
    self.driver.find_element(By.NAME, "password").send_keys("12345Aa!")
    # 11 | click | css=.solid | 
    self.driver.find_element(By.CSS_SELECTOR, ".solid").click()
  
