# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from NewsTailorDjangoApplication.tests.automated_tests.test_sign_in import sign_in


class TestMainPageButtons:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_faq(self):
        sign_in(self)
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "FAQ-button"))
        ).click()

    def test_about(self):
        sign_in(self)
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "About-page-button"))
        ).click()

    def test_logout(self):
        sign_in(self)
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "Logout-button"))
        ).click()
