# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from NewsTailorDjangoApplication.tests.automated_tests.test_sign_in import sign_in


class TestGenerate:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_generate(self):
        sign_in(self)
        config_form_input = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".configuration-form-input:nth-child(3)"))
        )
        config_form_input.click()

        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(3)")
        dropdown.find_element(By.XPATH, "//option[. = 'Sources']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".source-selection").click()
        self.driver.find_element(By.ID, "source-select-buttons").click()
        dropdown = self.driver.find_element(By.ID, "source-select-buttons")
        dropdown.find_element(By.XPATH, "//option[. = 'Category']").click()
        self.driver.find_element(By.ID, "source-select-buttons").click()
        dropdown = self.driver.find_element(By.ID, "source-select-buttons")
        dropdown.find_element(By.XPATH, "//option[. = 'Category']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(2)").click()
        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".configuration-form-input:nth-child(2)")
        dropdown.find_element(By.XPATH, "//option[. = 'Last 3 days']").click()
