# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestViewprofilepage():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_viewprofilepage(self):
        # Test name: view_profile_page
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("http://localhost:5173/")
        # 2 | setWindowSize | 1920x682 |
        self.driver.set_window_size(1920, 682)
        # 3 | click | css=.auth-button |
        self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
        # 4 | type | name=username | exampleUser@gmail.com
        self.driver.find_element(By.NAME, "username").send_keys("exampleUser@gmail.com")
        # 5 | type | name=password1 | 12345Aa!
        self.driver.find_element(By.NAME, "password1").send_keys("12345Aa!")
        # 6 | type | css=.sign-in-form > .signin-signup-input-field:nth-child(2) > input | exampleUser@gmail.com
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".sign-in-form > .signin-signup-input-field:nth-child(2) > input").send_keys(
            "exampleUser@gmail.com")
        # 8 | type | name=password | 12345Aa!
        self.driver.find_element(By.NAME, "password").send_keys("12345Aa!")
        # 9 | click | css=.sign-in-form |
        self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form").click()
        # 10 | click | css=.sign-in-form > .signin-signup-input-field:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form > .signin-signup-input-field:nth-child(3)").click()
        # 11 | click | id=logginButton |
        self.driver.find_element(By.ID, "logginButton").click()
        # 12 | click | id=userProfileLink |
        self.driver.find_element(By.ID, "userProfileLink").click()
