name: Django CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build Docker Image FE
      working-directory: NewsTailorFE/NewsTailorReactApplication
      run: |
        docker build -t newstailor_fe .

    - name: Build Docker Image BE
      working-directory: NewsTailorBE
      run: |
        docker build -t newstailor_be .

    - name: Build and Start Docker Containers
      run: |
        docker compose -f docker-compose.yaml up -d

    - name: Install Dependencies
      working-directory: NewsTailorBE
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run Backend Tests
      working-directory: NewsTailorBE
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        NEW_YORK_TIMES_API_KEY: ${{ secrets.NEW_YORK_TIMES_API_KEY }}
        NUMBER_OF_NEWS_ARTICLES: ${{ secrets.NUMBER_OF_NEWS_ARTICLES }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        coverage run manage.py test
        coverage report -m

    - name: Install Non-Snap Firefox and GeckoDriver
      run: |
          sudo apt-get purge -y firefox firefox-locale-en  # Remove the Snap version
          sudo snap remove firefox || true  # Ensure Snap version is removed
          sudo add-apt-repository -y ppa:mozillateam/ppa  # Add the Mozilla PPA
          echo 'Package: firefox*' | sudo tee -a /etc/apt/preferences.d/99firefox
          echo 'Pin: release o=LP-PPA-mozillateam' | sudo tee -a /etc/apt/preferences.d/99firefox
          echo 'Pin-Priority: 1001' | sudo tee -a /etc/apt/preferences.d/99firefox
          sudo apt-get update
          sudo apt-get install -y firefox
          wget -q https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

    - name: Install Selenium Dependencies
      working-directory: NewsTailorBE
      run: |
        pip install selenium

    - name: Run Selenium Tests
      working-directory: NewsTailorBE/NewsTailorDjangoApplication/tests/automated_tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python test_sign_in.py

    - name: Shut down Docker containers
      run: |
        docker compose down
