name: Deploy to Fly.io

on:
  push:
    branches:
      - deployment-docs

jobs:
  deploy:
    name: Deploy Frontend and Backend to Fly.io
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Fly.io CLI
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
          export PATH="$HOME/.fly/bin:$PATH"

      # Step 3: Authenticate with Fly.io
      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      # Step 4: Set Fly.io Secrets
      - name: Set Fly.io Secrets
        working-directory: NewsTailorBE
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set SECRET_KEY="${{ secrets.SECRET_KEY }}" \
                            DB_NAME="${{ secrets.DB_NAME }}" \
                            DB_USER="${{ secrets.DB_USER }}" \
                            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
                            DB_HOST="postgresql://newstailor-db.flycast" \
                            DB_PORT="${{ secrets.DB_PORT }}" \
                            GUARDIAN_API_KEY="${{ secrets.GUARDIAN_API_KEY }}" \
                            NEWS_API_KEY="${{ secrets.NEWS_API_KEY }}" \
                            NEW_YORK_TIMES_API_KEY="${{ secrets.NEW_YORK_TIMES_API_KEY }}" \
                            NUMBER_OF_NEWS_ARTICLES="${{ secrets.NUMBER_OF_NEWS_ARTICLES }}" \
                            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"

      # Step 5: Deploy Backend
      - name: Deploy Backend to Fly.io
        working-directory: NewsTailorBE
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: postgresql://newstailor-db.flycast
          DB_PORT: ${{ secrets.DB_PORT }}
          GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NEW_YORK_TIMES_API_KEY: ${{ secrets.NEW_YORK_TIMES_API_KEY }}
          NUMBER_OF_NEWS_ARTICLES: ${{ secrets.NUMBER_OF_NEWS_ARTICLES }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: flyctl deploy --app newstailorbe

      # Step 6: Deploy Frontend
      - name: Deploy Frontend to Fly.io
        working-directory: NewsTailorFE/NewsTailorReactApplication
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --app newstailorreactapplication
