name: Deploy to Fly.io

on:
  push:
    branches:
      - deployment-docs
      - development
  pull_request:
    branches:
      - deployment-docs
      - development

jobs:
  deploy:
    name: Deploy Frontend and Backend to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      - name: Set Fly.io Secrets
        working-directory: NewsTailorBE
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          # Set VITE_API_URL based on branch
          if [[ "$REF_NAME" == "development" ]]; then
            VITE_API_URL="https://newstailorbe-prod.fly.dev/"
          else
            VITE_API_URL="https://newstailorbe.fly.dev/"
          fi

          echo "VITE_API_URL is set to: $VITE_API_URL"

          flyctl secrets set SECRET_KEY="${{ secrets.SECRET_KEY }}" \
                            DB_NAME="postgres" \
                            DB_USER="postgres" \
                            DB_PASSWORD="${{ secrets.DB_PASSWORD_FLY }}" \
                            DB_HOST="newstailor-db.flycast" \
                            DB_PORT="5432" \
                            DB_URL="${{ secrets.DB_URL_FLY }}" \
                            GUARDIAN_API_KEY="${{ secrets.GUARDIAN_API_KEY }}" \
                            NEWS_API_KEY="${{ secrets.NEWS_API_KEY }}" \
                            NEW_YORK_TIMES_API_KEY="${{ secrets.NEW_YORK_TIMES_API_KEY }}" \
                            NUMBER_OF_NEWS_ARTICLES="${{ secrets.NUMBER_OF_NEWS_ARTICLES }}" \
                            VITE_API_URL="$VITE_API_URL" \
                            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"

      - name: Deploy Backend to Fly.io
        working-directory: NewsTailorBE
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$REF_NAME" == "development" ]]; then
            flyctl deploy --config fly.prod.toml --app newstailorbe-prod;
          else
            flyctl deploy --config fly.toml --app newstailorbe;
          fi

      - name: Deploy Frontend to Fly.io
        working-directory: NewsTailorFE/NewsTailorReactApplication
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$REF_NAME" == "development" ]]; then
            flyctl deploy --config fly.prod.toml --app newstailorreactapplication-prod;
          else
            flyctl deploy --config fly.toml --app newstailorreactapplication;
          fi
