name: Deploy to Fly.io

on:
  push:
    branches:
      - deployment-docs

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Fly.io CLI
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      # Step 3: Authenticate Fly.io
      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      # Step 4: Deploy to Fly.io
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ "${{ github.ref_name }}" == "deployment-docs" ]; then
            flyctl deploy --app newstailorreactapplication
          fi