name: Deploy to Fly.io

on:
  push:
    branches:
      - deployment-docs

jobs:
  deploy:
    name: Deploy Frontend and Backend to Fly.io
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Fly.io CLI
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
          export PATH="$HOME/.fly/bin:$PATH"

      # Step 3: Authenticate with Fly.io
      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      # Step 4: Deploy Backend
      - name: Deploy Backend to Fly.io
        working-directory: NewsTailorBE
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --app newstailorbe

      # Step 5: Deploy Frontend
      - name: Deploy Frontend to Fly.io
        working-directory: NewsTailorFE/NewsTailorReactApplication
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --app newstailorreactapplication
